/**
 * Created with IntelliJ IDEA.
 * User: sonalraj
 * Date: 21/11/13
 * Time: 11:49
 * To change this template use File | Settings | File Templates.
 */
public class EvenFibonacciSum {
    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    public static boolean isEven(int n)
    {
        //last bit of even number is zero and odd number is 1
        if((n&1)==0)
            return true;
        return false;
    }

    public static void checkFibbo(int a, int b, int n, int sum)
    {
        int fibo = a+b;
        if(isEven(fibo))
            sum+=fibo;
        a=b;
        b=fibo;
        if(b>=n)
        {
            System.out.println(sum);
            return;
        }
        checkFibbo(a,b,n,sum);
    }

    public static void main(String[] args)
    {
        checkFibbo(0,1,4000000,0);
    }
}
